---
"parserOptions":
  "ecmaVersion": 6
  "sourceType": "script"

"extends":
  - "strict"
  - "strict/es6"

"rules":
  "linebreak-style": [ "error", "unix" ]
  "quotes": [ "error", "single" ]
  "newline-after-var": [ "error", "always" ]
